import type { Metadata } from 'next';
import Footer from '@/components/layouts/Footer';
import Navbar from '@/components/layouts/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function StaticRootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className={`bg-[#202124] w-full min-h-screen text-white`}>
			<Navbar />
			{children}
			<Footer />
		</main>
	);
}
