import type { Metadata } from 'next';
import './globals.css';
import { Cormorant_Garamond, PT_Sans } from 'next/font/google';

const cormorantGaramond = Cormorant_Garamond({
	weight: ['300', '400', '500', '600', '700'],
	display: 'swap',
	subsets: ['latin'],
});

const ptSans = PT_Sans({
	weight: ['400', '700'],
	display: 'swap',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${cormorantGaramond.className} ${ptSans.className} font-["Coromorant_Garamond"]`}
			>
				{children}
			</body>
		</html>
	);
}
